### ISSUE TITLE
Double quotes in strings aren't escaped

### ISSUE THREAD

**Issue by rowanmanning** [philbooth/bfj#27]
Double quotes in strings aren't escaped, which causes invalid JSON to be produced. You can reproduce with the following:

```js
var stream = bfj.streamify({
    foo: 'bar"baz'
});
stream.pipe(process.stdout);
```

which outputs

```json
{"foo":"bar"baz"}
```

The [relevant code is here](https://github.com/philbooth/bfj/blob/master/src/streamify.js#L174), and I started working on a fix, but there are several routes I could take. I'd like your input before I continue:

1. Fix for just this case (make sure double quotes are escaped). I don't like this option as it feels like we'll potentially hit the same issue for other characters.

2. Use `JSON.stringify` on the string value. I tried this and it works, but some integration tests fail. However they probably _shouldn't_ fail, because the output JSON is correct:
    ```js
    function string (s) {
        value(JSON.stringify(s));
    }
    ```

3. Use something like [jsesc](https://github.com/mathiasbynens/jsesc) (or similar, this looks potentially unmaintained) to escape the strings. The issue is it possibly does more than we need it to and introduces another dependency.

I'm preferring option 2, but let me know how you'd like me to proceed.

**Comment by rowanmanning** [comment]
Actually the [integration test mentioned in option 2](https://github.com/rowanmanning/bfj/blob/master/test/integration.js#L225) is technically incorrect, it's testing that the output string contains a tab character:

```js
assert.strictEqual(result, '"foo\tbar"');
```

Line breaks in JSON strings are invalid, so sequences like `\n` and `\t` should have the back-slash escaped. The test should be:

```js
assert.strictEqual(result, '"foo\\tbar"');
```

which currently doesn't pass. Highlighted the difference between bfj and `JSON.stringify` here:

```js
{"foo":"bar\tbaz"} // JSON.stringify (escape sequence)
{"foo":"bar	baz"}  // bfj (tab character)
```

So I'm going to open a PR with option 2 :)

**Comment by philbooth** [comment]
Oh dear, how embarrassing! :blush:

Option `2` is fine, but it's at the wrong level of abstraction. Instead you should do it at [line 97 of `eventify.js`](https://github.com/philbooth/bfj/blob/master/src/eventify.js#L97), so that the fix applies for direct importers of that module.

**Comment by rowanmanning** [comment]
Ah cool, thanks! wouldn't have spotted that. On it :+1:
