### ISSUE TITLE
Add buffering for streamify

### ISSUE THREAD

**Issue by be5invis** [philbooth/bfj#42]
Emitting one character by character may be slow on some environments.

**Comment by philbooth** [comment]
Yeah, I've been letting this project slide recently. I'll try and make time for it at the weekend! 😄

**Comment by be5invis** [comment]
@philbooth I saw that you are already using a "json" variable for temporary buffer.

**Comment by philbooth** [comment]
Switched to a fixed-length circular array in e773a94 / release `3.1.0`. Closing.
