### ISSUE TITLE
node v7.x: DeprecationWarning and UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by jbilcke** [philbooth/bfj#44]
Hi,

there are some scary "unhandled rejection" warnings when running the app under Node 7 (I tested 7.2.1, I suppose it concerns other 7.x builds as well)

my test program:

```javascript
var bfj = require('bfj');
bfj.read("path/to/my/json").then(data => console.log("OK:", data))
```

 I have the following output:

```
(node:76859) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): undefined
(node:76859) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
OK:
{{{ my json content }}}
```

I though I did something wrong, so I made a version to catch any kind of error:

```javascript
var bfj = require('bfj');
try {
  bfj.read("path/to/my/json")
    .then(data => console.log("OK:", data))
    .catch(err => console.error("NOT OK: ", err))
} catch (exc) {
  console.error("DEFINITELY NOT OK: ", exc)
}
```

but I still have the same output:

```
(node:76859) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): undefined
(node:76859) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
OK:
{{{ my json content }}}
```

**Comment by philbooth** [comment]
Hmm, thanks for reporting. Looks like I'm probably forgetting to the return promise somewhere, I'll dig into it properly over the weekend.

**Comment by philbooth** [comment]
Hey @jbilcke, I've fixed a bunch of unhandled rejection warnings, hopefully that covers the ones you saw. When you get a moment, could you try out version 2.1.1 and let me know if it fixes your issue?

**Comment by jbilcke** [comment]
oh! thank you @philbooth!

 I hope this wasn't too cumbersome (you had to put a return everywhere?)

I tested version 2.1.2 and it works nicely now!

**Comment by philbooth** [comment]
No worries, it needed doing. I hadn't done much with promises before when I wrote this, so there were anti-patterns all over the place. The code's much better now, so thanks for reporting it! 😄
