### ISSUE TITLE
bfj is awesome, but a bit slow

### ISSUE THREAD

**Issue by march1993** [philbooth/bfj#47]
In my case, it took minutes to write a 100MiB sized JSON file.
Are there any steps that I can do to speed up the write method?

**Comment by philbooth** [comment]
The slowness is mostly because of all the calls to `setImmediate` I added to make it async. The balance is definitely wrong there, I opted for the simplest implementation rather than an otimised one.

It should be pretty straightforward to make some good improvements, I'll take a look this week.

**Comment by axe312ger** [comment]
Super nice!

**Comment by philbooth** [comment]
Okay, in `4.0.0` I've made a change to drastically reduce the frequency of calls to `setImmediate`. I'm seeing about 30% improvement in the speed to write a 54 mb JSON file to disk.

It's not perfect but it's a start, I'll see if I can make further improvements elsewhere too.

**Comment by march1993** [comment]
super awesome！

**Comment by rgranger** [comment]
bfj is awesome and the api is exactly what i needed !

But I find it extremely slow :

On my data object : ~10 Mo of data

JSON.stringify : < ~200 ms
bfj.stringify : > 110 000 ms

As my application boot with this dataset, I can not afford a 110 s payload.

I wanted to use this module to stream the initial json data i send to the client because, when i do JSON.stringify() and the application is under heavy load (via websockets), each new connection put the 200ms freeze on the ongoing traffic, but i fail to see any efficient working solution on streaming huge json dataset (it works fine as a file, but not as in memory javascript object)

**Comment by philbooth** [comment]
I'll have another look into this, specifically `stringify`, at some point in the next couple of weeks. Thanks for (re-)raising it.

> Moreover I had to set option { circular: 'ignore' } to get it to work, whereas i'm pretty sure there is no circular reference in my dataset.

Opened as #53.

**Comment by philbooth** [comment]
Depending on the shape of your data, version `4.1.1` may improve the times you're seeing for `stringify`, `streamify`, `write` and `eventify`.

**Comment by rgranger** [comment]
Hi ! Great job and thanks for the really fast fixes !

On my dataset, bfj.stringify() is now taking < 20s (which is a great improvement since it was 110s before)

I really hope this can be further reduced since i cannot afford more than 2-3 seconds of payload maximum

**Comment by philbooth** [comment]
@rgranger, can you give me a really rough, ball-park estimate for what percentage of properties in your data are strings? And roughly how deep does the object nesting go?

**Comment by rgranger** [comment]
The object is deeply nested : I counted 15 levels on what I think is the deepest branch.

I don't think we have many strings. The vast majority of 'leaf' values are numbers and booleans.
We also have a few very big Arrays that contains a lot of strings.

The vast majority of the data is Object containing Objects

**Comment by philbooth** [comment]
Thanks! I'll do some profiling with something similar and see what I can come up with.

**Comment by philbooth** [comment]
I've got no more perf improvements lined up for now, so closing this issue.
