### ISSUE TITLE
Writing giant JSON results in out of memory error

### ISSUE THREAD

**Issue by majuss** [philbooth/bfj#54]
Hi guys!

I'am trying to write a giant hierarchical JSON-tree to the disk. It's getting collected with a database query. Then I use the simple code:

```
bfj.write('tree.json', body.result)
        .then(() => {
            console.log("Finished generating sunburst tree");
          });

```
To write the file to disk. nodejs crashes after ~20 minutes with the following:

```
<--- Last few GCs --->

[32332:0x55eff042e690]  1725813 ms: Mark-sweep 1232.9 (1783.1) -> 1232.9 (1783.1) MB, 2781.0 / 0.0 ms  allocation failure GC in old space requested
[32332:0x55eff042e690]  1728684 ms: Mark-sweep 1232.9 (1783.1) -> 1232.9 (1743.1) MB, 2871.4 / 0.0 ms  last resort
[32332:0x55eff042e690]  1731638 ms: Mark-sweep 1232.9 (1743.1) -> 1232.9 (1736.1) MB, 2954.2 / 0.0 ms  last resort


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0xdbe8d89cca1 <JSObject>
    1: /* anonymous */(aka /* anonymous */) [/home/marius/globi-parasites/node_modules/hoopy/index.js:~13] [pc=0x18374ecef6e0](this=0x217ec0b49c41 <JSProxy>,by=65536)
    2: addJson(aka addJson) [/home/marius/globi-parasites/node_modules/bfj/src/streamify.js:~92] [pc=0x18374ecddf90](this=0xdbe8d882241 <undefined>,chunk=0xdbe8d8b9371 <String[1]: [>)
    3: array [/home/marius/globi-parasites/node_...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0x55efef40d3ee [node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Factory::NewUninitializedFixedArray(int) [node]
 6: 0x55efeef5895d [node]
 7: v8::internal::Runtime_GrowArrayElements(int, v8::internal::Object**, v8::internal::Isolate*) [node]
 8: 0x18374eb840dd
Aborted
```

The tree consists of 1.7 Mio. elements. I already tried to allocate nodejs more RAM: `--max_old_space_size=58000` but it had no effect (I have 0.5 TB of RAM).
I thought bfj would somehow "stream" the JSON to disk and could avoid memory problems? Am I wrong?

Cheers

Majuss

**Comment by philbooth** [comment]
> I thought bfj would somehow "strem" the JSON to disk and could avoid memory problems? Am I wrong?

You're not wrong, that's how it's supposed to work but, as you can see, there are problems I'm still trying to get to the bottom of. I'll try and dig into it some more this weekend, sorry I can't be more helpful than that for now.

**Comment by philbooth** [comment]
Hey @majuss, I've had a stab at fixing this in version `4.2.0`. Can you give it a try and let me know whether it works for you?

A couple of general points about the fix for anyone else that might be interested:

* Fix only applies to `write`, `stringify` and `streamify` methods.
* A side-effect of the fix is that, sadly, those methods are now a bit slower than they were in `4.1.1`.

**Comment by majuss** [comment]
It works now! The resulting 11 MB json is crashing d3 but thats not your problem :) Thanks for the fix!

**Comment by philbooth** [comment]
That's great to hear, thanks for letting me know @majuss! Good luck with d3! 😄
