### ISSUE TITLE
Link to a package that simplifies bfj.walk() a little

### ISSUE THREAD

**Issue by hash-bang** [philbooth/bfj#60]
Thanks for the excellent module.

I found I end up writing the same parser for very large data sets in the form of collections so I've written [bfj-collections](https://github.com/hash-bang/bfj-collections) to simplify the parsing of this subset of JSON formats a little. I thought you may want to stick it in your README somewhere to avoid what is probably a common problem.

It really just wraps the `bfj.walk()` function and provides an additional emitter which fires when everything from the first level of the JSON tree has finished parsing.

**Comment by philbooth** [comment]
Nice! Link added to the readme in 11eacb8.
