### ISSUE TITLE
Support for parsing ndjson?

### ISSUE THREAD

**Issue by mfogel** [philbooth/bfj#61]
Hi, thanks for your work on bfj.

I'm trying to parse an [ndjson](http://ndjson.org/) readable stream. Best I can tell, this isn't currently supported by the library in any form - `parse()` of course returns a promise for *one* json object.

Would you be open to either:

 * an additional option to `parse()` that tells it to only consume as much of the input stream as it needs to in order to parse out one json object? It could then [unshift](https://nodejs.org/api/stream.html#stream_readable_unshift_chunk) back to the input stream any data it had consumed that wasn't part of that json object it had successfully parsed out. The caller could then try to parse another json object out if it so desires. Right now it appears that current behavior is that the entire stream is consumed, emitting an error in the process.
 * another method, something like `parsend()` - which would return a promise that would resolve to an array of json objects.

Let me know what you think, cheers.

**Comment by philbooth** [comment]
@mfogel, I like it!

For implementation, I would prefer just to add an option than an entirely new method. But I'm also wondering if it could be the standard behaviour, kicking in when we detect the trailing `,`. Seems like that could work without affecting existing usage?

**Comment by philbooth** [comment]
s/`,`/`\n`/

**Comment by philbooth** [comment]
@mfogel, I took a crack at implementing this in e87672a505df2e4c34fd9ac1dc424c856310c6d8, published to npm as version `5.3.0`. You can use it by passing the `ndjson` option to `parse` or `walk`. Let me know if you get any problems!
